/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    accounts: Account;
    media: Media;
    'lscs-article-category': LscsArticleCategory;
    'lscs-articles': LscsArticle;
    'lscs-article-authors': LscsArticleAuthor;
    'lscs-partners': LscsPartner;
    'lscs-awards': LscsAward;
    'lscs-web-assets': LscsWebAsset;
    'archerbytes-article-category': ArcherbytesArticleCategory;
    'archerbytes-articles': ArcherbytesArticle;
    'sgar-units': SgarUnit;
    'sgar-clusters': SgarCluster;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'lscs-article-category': LscsArticleCategorySelect<false> | LscsArticleCategorySelect<true>;
    'lscs-articles': LscsArticlesSelect<false> | LscsArticlesSelect<true>;
    'lscs-article-authors': LscsArticleAuthorsSelect<false> | LscsArticleAuthorsSelect<true>;
    'lscs-partners': LscsPartnersSelect<false> | LscsPartnersSelect<true>;
    'lscs-awards': LscsAwardsSelect<false> | LscsAwardsSelect<true>;
    'lscs-web-assets': LscsWebAssetsSelect<false> | LscsWebAssetsSelect<true>;
    'archerbytes-article-category': ArcherbytesArticleCategorySelect<false> | ArcherbytesArticleCategorySelect<true>;
    'archerbytes-articles': ArcherbytesArticlesSelect<false> | ArcherbytesArticlesSelect<true>;
    'sgar-units': SgarUnitsSelect<false> | SgarUnitsSelect<true>;
    'sgar-clusters': SgarClustersSelect<false> | SgarClustersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'viewer' | 'none';
  domain: 'lscs' | 'global';
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  name?: string | null;
  picture?: string | null;
  user: number | User;
  issuerName: string;
  scope?: string | null;
  sub: string;
  access_token?: string | null;
  passkey?: {
    credentialId: string;
    publicKey:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    counter: number;
    transports:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    deviceType: string;
    backedUp: boolean;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-article-category".
 */
export interface LscsArticleCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-articles".
 */
export interface LscsArticle {
  id: number;
  title: string;
  subtitle: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  mdContent?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  author: number | LscsArticleAuthor;
  category: number | LscsArticleCategory;
  tags?: string[] | null;
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-article-authors".
 */
export interface LscsArticleAuthor {
  id: number;
  name: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-partners".
 */
export interface LscsPartner {
  id: number;
  name: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-awards".
 */
export interface LscsAward {
  id: number;
  awardName: string;
  year: number;
  projectName: string;
  rank: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-web-assets".
 */
export interface LscsWebAsset {
  id: number;
  title: string;
  hero?: {
    image?: (number | null) | Media;
  };
  whoAreWe?: {
    image?: (number | null) | Media;
  };
  whatWeDo?: {
    image1?: (number | null) | Media;
    image2?: (number | null) | Media;
    image3?: (number | null) | Media;
    image4?: (number | null) | Media;
  };
  about?: {
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archerbytes-article-category".
 */
export interface ArcherbytesArticleCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archerbytes-articles".
 */
export interface ArcherbytesArticle {
  id: number;
  title: string;
  subtitle: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  mdContent?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  author: number | LscsArticleAuthor;
  category: number | ArcherbytesArticleCategory;
  tags?: string[] | null;
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sgar-units".
 */
export interface SgarUnit {
  id: number;
  'unit-name': string;
  slug: string;
  cluster?: (number | null) | SgarCluster;
  description: string;
  'form-link': string;
  logo?: (number | null) | Media;
  'main-pub'?: (number | null) | Media;
  'org-chart'?: (number | null) | Media;
  'application-process'?: string | null;
  'application-timeline'?: string | null;
  'executive-board'?:
    | {
        'full-name': string;
        position: string;
        email: string;
        'telegram-username'?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  committees?:
    | {
        'committee-name': string;
        description: string;
        requirements?: string | null;
        position?:
          | {
              'position-name': string;
              status: 'open' | 'closed';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sgar-clusters".
 */
export interface SgarCluster {
  id: number;
  'cluster-name': string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'lscs-article-category';
        value: number | LscsArticleCategory;
      } | null)
    | ({
        relationTo: 'lscs-articles';
        value: number | LscsArticle;
      } | null)
    | ({
        relationTo: 'lscs-article-authors';
        value: number | LscsArticleAuthor;
      } | null)
    | ({
        relationTo: 'lscs-partners';
        value: number | LscsPartner;
      } | null)
    | ({
        relationTo: 'lscs-awards';
        value: number | LscsAward;
      } | null)
    | ({
        relationTo: 'lscs-web-assets';
        value: number | LscsWebAsset;
      } | null)
    | ({
        relationTo: 'archerbytes-article-category';
        value: number | ArcherbytesArticleCategory;
      } | null)
    | ({
        relationTo: 'archerbytes-articles';
        value: number | ArcherbytesArticle;
      } | null)
    | ({
        relationTo: 'sgar-units';
        value: number | SgarUnit;
      } | null)
    | ({
        relationTo: 'sgar-clusters';
        value: number | SgarCluster;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  domain?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  user?: T;
  issuerName?: T;
  scope?: T;
  sub?: T;
  access_token?: T;
  passkey?:
    | T
    | {
        credentialId?: T;
        publicKey?: T;
        counter?: T;
        transports?: T;
        deviceType?: T;
        backedUp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-article-category_select".
 */
export interface LscsArticleCategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-articles_select".
 */
export interface LscsArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  featuredImage?: T;
  content?: T;
  mdContent?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  author?: T;
  category?: T;
  tags?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-article-authors_select".
 */
export interface LscsArticleAuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  avatar?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-partners_select".
 */
export interface LscsPartnersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-awards_select".
 */
export interface LscsAwardsSelect<T extends boolean = true> {
  awardName?: T;
  year?: T;
  projectName?: T;
  rank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lscs-web-assets_select".
 */
export interface LscsWebAssetsSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        image?: T;
      };
  whoAreWe?:
    | T
    | {
        image?: T;
      };
  whatWeDo?:
    | T
    | {
        image1?: T;
        image2?: T;
        image3?: T;
        image4?: T;
      };
  about?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archerbytes-article-category_select".
 */
export interface ArcherbytesArticleCategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archerbytes-articles_select".
 */
export interface ArcherbytesArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  featuredImage?: T;
  content?: T;
  mdContent?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  author?: T;
  category?: T;
  tags?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sgar-units_select".
 */
export interface SgarUnitsSelect<T extends boolean = true> {
  'unit-name'?: T;
  slug?: T;
  cluster?: T;
  description?: T;
  'form-link'?: T;
  logo?: T;
  'main-pub'?: T;
  'org-chart'?: T;
  'application-process'?: T;
  'application-timeline'?: T;
  'executive-board'?:
    | T
    | {
        'full-name'?: T;
        position?: T;
        email?: T;
        'telegram-username'?: T;
        photo?: T;
        id?: T;
      };
  committees?:
    | T
    | {
        'committee-name'?: T;
        description?: T;
        requirements?: T;
        position?:
          | T
          | {
              'position-name'?: T;
              status?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sgar-clusters_select".
 */
export interface SgarClustersSelect<T extends boolean = true> {
  'cluster-name'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}